In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
df1 = pd.read_csv('dataset_encoded.csv')
df1.head(10)

gender   age  hypertension  heart_disease  ever_married  Residence_type  \
0       0  67.0             0              1             1               1   
1       0  80.0             0              1             1               0   
2       1  49.0             0              0             1               1   
3       1  79.0             1              0             1               0   
4       0  81.0             0              0             1               1   
5       0  74.0             1              1             1               0   
6       1  69.0             0              0             0               1   
7       1  78.0             0              0             1               1   
8       1  81.0             1              0             1               0   
9       1  61.0             0              1             1               0   

   avg_glucose_level   bmi  stroke  work_type_Private  \
0            168.805  36.6       1                1.0   
1            105.920  32.5       1                1.0   
2            168.805  34.4       1                1.0   
3            168.805  24.0       1                0.0   
4            168.805  29.0       1                1.0   
5             70.090  27.4       1                1.0   
6             94.390  22.8       1                1.0   
7             58.570  24.2       1                1.0   
8             80.430  29.7       1                1.0   
9            120.460  36.8       1                0.0   

   work_type_Self-employed  work_type_children  \
0                      0.0                 0.0   
1                      0.0                 0.0   
2                      0.0                 0.0   
3                      1.0                 0.0   
4                      0.0                 0.0   
5                      0.0                 0.0   
6                      0.0                 0.0   
7                      0.0                 0.0   
8                      0.0                 0.0   
9                      0.0                 0.0   

   smoking_status_formerly smoked  smoking_status_never smoked  \
0                             1.0                          0.0   
1                             0.0                          1.0   
2                             0.0                          0.0   
3                             0.0                          1.0   
4                             1.0                          0.0   
5                             0.0                          1.0   
6                             0.0                          1.0   
7                             0.0                          0.0   
8                             0.0                          1.0   
9                             0.0                          0.0   

   smoking_status_smokes  
0                    0.0  
1                    0.0  
2                    1.0  
3                    0.0  
4                    0.0  
5                    0.0  
6                    0.0  
7                    0.0  
8                    0.0  
9                    1.0

In [3]:
df2 = pd.read_csv('stroke_cases_only.csv')
df2.head(10)

HeartDiseaseorAttack  HighBP  HighChol  CholCheck   BMI  Smoker  Stroke  \
0                   0.0     0.0       1.0        1.0  33.0     1.0     1.0   
1                   1.0     1.0       1.0        1.0  22.0     0.0     1.0   
2                   1.0     1.0       1.0        1.0  37.0     1.0     1.0   
3                   0.0     1.0       1.0        1.0  34.0     1.0     1.0   
4                   0.0     0.0       0.0        1.0  28.0     1.0     1.0   
5                   1.0     1.0       1.0        1.0  38.0     1.0     1.0   
6                   1.0     1.0       1.0        1.0  23.0     1.0     1.0   
7                   0.0     1.0       1.0        1.0  23.0     0.0     1.0   
8                   0.0     0.0       1.0        1.0  29.0     1.0     1.0   
9                   1.0     1.0       1.0        1.0  25.0     1.0     1.0   

   Diabetes  PhysActivity  Fruits  ...  AnyHealthcare  NoDocbcCost  GenHlth  \
0       0.0           1.0     0.0  ...            1.0          1.0      4.0   
1       0.0           0.0     1.0  ...            1.0          0.0      3.0   
2       2.0           0.0     0.0  ...            1.0          0.0      5.0   
3       2.0           1.0     0.0  ...            1.0          0.0      4.0   
4       0.0           0.0     1.0  ...            1.0          1.0      4.0   
5       0.0           0.0     1.0  ...            1.0          0.0      4.0   
6       2.0           0.0     1.0  ...            1.0          1.0      1.0   
7       0.0           1.0     1.0  ...            1.0          0.0      3.0   
8       2.0           1.0     0.0  ...            1.0          1.0      4.0   
9       0.0           1.0     0.0  ...            1.0          0.0      4.0   

   MentHlth  PhysHlth  DiffWalk  Sex   Age  Education  Income  
0      30.0      28.0       0.0  0.0   4.0        6.0     2.0  
1      30.0       0.0       1.0  0.0  12.0        4.0     4.0  
2       0.0       0.0       1.0  1.0  10.0        6.0     5.0  
3       0.0       7.0       1.0  0.0   9.0        5.0     4.0  
4      15.0      30.0       1.0  0.0   7.0        4.0     3.0  
5      10.0       5.0       1.0  1.0  11.0        5.0     6.0  
6       2.0       0.0       0.0  0.0   7.0        5.0     3.0  
7       0.0       0.0       1.0  1.0  13.0        4.0     4.0  
8      30.0      10.0       1.0  0.0  11.0        5.0     2.0  
9       0.0      30.0       1.0  1.0  12.0        5.0     5.0  

[10 rows x 22 columns]

In [4]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4981 entries, 0 to 4980
Data columns (total 15 columns):
 #   Column                          Non-Null Count  Dtype  
---  ------                          --------------  -----  
 0   gender                          4981 non-null   int64  
 1   age                             4981 non-null   float64
 2   hypertension                    4981 non-null   int64  
 3   heart_disease                   4981 non-null   int64  
 4   ever_married                    4981 non-null   int64  
 5   Residence_type                  4981 non-null   int64  
 6   avg_glucose_level               4981 non-null   float64
 7   bmi                             4981 non-null   float64
 8   stroke                          4981 non-null   int64  
 9   work_type_Private               4981 non-null   float64
 10  work_type_Self-employed         4981 non-null   float64
 11  work_type_children              4981 non-null   float64
 12  smoking_status_formerly smoked  49

array([168.805, 105.92 ,  70.09 , ...,  84.94 ,  95.02 ,  83.94 ],
      shape=(3315,))

In [5]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10292 entries, 0 to 10291
Data columns (total 22 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   HeartDiseaseorAttack  10292 non-null  float64
 1   HighBP                10292 non-null  float64
 2   HighChol              10292 non-null  float64
 3   CholCheck             10292 non-null  float64
 4   BMI                   10292 non-null  float64
 5   Smoker                10292 non-null  float64
 6   Stroke                10292 non-null  float64
 7   Diabetes              10292 non-null  float64
 8   PhysActivity          10292 non-null  float64
 9   Fruits                10292 non-null  float64
 10  Veggies               10292 non-null  float64
 11  HvyAlcoholConsump     10292 non-null  float64
 12  AnyHealthcare         10292 non-null  float64
 13  NoDocbcCost           10292 non-null  float64
 14  GenHlth               10292 non-null  float64
 15  MentHlth           

In [16]:
df2['Diabetes'].unique()  # Para la columna BMI

array([0., 2., 1.])

In [20]:
df1['avg_glucose_level'].unique()

array([168.805, 105.92 ,  70.09 , ...,  84.94 ,  95.02 ,  83.94 ],
      shape=(3315,))

In [10]:
# Cargar el dataset original
df1 = pd.read_csv('dataset_encoded.csv')

# Hacer una copia para trabajar
f1 = df1.copy()
f2 = df2.copy()

In [ ]:

f2_filtrado = f2.rename(columns={
    'Age': 'age',
    'BMI': 'bmi',
    'Sex': 'gender',
    'HighBP': 'hypertension',
    'HeartDiseaseorAttack': 'heart_disease',
    'Stroke': 'stroke'
})


columnas_comunes = ['age', 'bmi', 'gender', 'hypertension', 'heart_disease', 'stroke']
f1_filtrado = f1[columnas_comunes]
f2_filtrado = f2_filtrado[columnas_comunes]


df_concatenado = pd.concat([f1_filtrado, f2_filtrado], ignore_index=True)


print(df_concatenado['stroke'].value_counts())

stroke
1.0    10540
0.0     4733
Name: count, dtype: int64


In [15]:
df_concatenado.to_csv('dataset_concatenado.csv', index=False)

In [14]:
df_concatenado.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15273 entries, 0 to 15272
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   age            15273 non-null  float64
 1   bmi            15273 non-null  float64
 2   gender         15273 non-null  float64
 3   hypertension   15273 non-null  float64
 4   heart_disease  15273 non-null  float64
 5   stroke         15273 non-null  float64
dtypes: float64(6)
memory usage: 716.1 KB
